version: "2"

services:
  app:
    # TODO: Replace this with your image name
    image: slashdeploy/docker-ruby-boilerplate
    build: .
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:3

  tests:
    build: .
    environment:
      MONGODB_URI: mongodb://mongo
    depends_on:
      - mongo
    volumes:
      - .:/app

  smoke:
    build: .
    command: ruby test/smoke.rb http://app:8080
