#!/usr/bin/env bash

set -euo pipefail

if ! make -q Gemfile.lock &> /dev/null; then
	make Gemfile.lock
fi

if ! make -q fixtures.yml &> /dev/null; then
	make fixtures.yml
fi

docker-compose build tests
docker-compose run tests script/load-fixtures
docker-compose run --rm -p 9090:9090 tests \
	bundle exec shotgun --server puma --host 0.0.0.0 --port 9090 script/shotgun.ru
