#!/usr/bin/env ruby

require_relative '../src/app'

logger = Logger::Better.new($stdout).tap do |log|
	log.level = ENV.fetch('LOG_LEVEL', 'info').to_sym
end

repo = MongoRepo.new(Mongo::Client.new(ENV.fetch('MONGODB_URI'), {
	logger: logger
}))

logger.info('shutgun') { 'Preparing repo' }

repo.clear
repo.setup

logger.info('shotgun') { 'Loading fixtures' }

YAML.load_file('fixtures.yml').each_pair do |_collection, items|
  items.each do |item|
    repo << item
  end
end
